"""A null population: random specs drawn from the same space a searcher samples.

This exists for one test, and that test is the one number that says whether
autonomous promotion is safe. `paper_shadow_sessions` is 0, so nothing stands
between a generated strategy and real money except the promotion gate — and the
only way to know whether that gate holds is to point a population of specs with
**no edge by construction** at it and count how many get through.

Two properties make the population a fair test rather than a straw man:

**The specs are drawn from the real grammar.** Same operators, same feature
library, same depth and node bounds a searcher would use. A population of
deliberately silly specs would be rejected by the schema rather than by the
gate, and would prove nothing about the gate.

**The data has no edge by construction, not by measurement.** A random walk
with zero drift, so any Sharpe a spec shows is sampling noise. Using real prices
would confound "the gate refused a noise strategy" with "this decade happened
to be a bear market", and the question here is about the gate.

The generator is deterministic given a seed, so a failure is reproducible.
`generate` never returns an invalid spec: the grammar bounds are enforced while
building rather than by retrying until something validates, so a run's spec
count is the count asked for.
"""

from __future__ import annotations

import random
from collections.abc import Sequence
from datetime import UTC, datetime, timedelta
from decimal import Decimal

from tb.data.provider import Bar, Provenance, Resolution, Session
from tb.features.pipeline import FEATURE_LIBRARY
from tb.strategy.dsl.schema import MAX_LOOKBACK, MIN_LOOKBACK, StrategySpec

# Lookbacks a generated spec may ask for. Bounded well inside the grammar's own
# limits so a fixture of a few hundred bars can actually evaluate them: a spec
# whose lookback exceeds the window evaluates to UNKNOWN at every decision and
# is recorded as a strategy that found no opportunities, which is a false
# negative that looks exactly like a true one.
NULL_LOOKBACKS = (5, 10, 20, 50, 100)

# Edges a generated spec may declare, in bps. Spread across the band the cost
# gate cares about: below ~121bps a US round trip is unaffordable, so a
# population entirely below it would be refused by the cost gate and would
# never reach the statistical checks this test is about.
NULL_EDGES = (Decimal("150"), Decimal("250"), Decimal("350"), Decimal("450"))

_COMPARISONS = ("lt", "lte", "gt", "gte")

# Features whose values are comparable against each other. `zscore` and
# `return_pct` live on a different scale from `sma` and `last`, and a spec
# comparing a price against a z-score is not a silly spec a searcher would
# avoid — it is one the grammar permits and a searcher will generate — so the
# population includes them.
_FEATURES = tuple(sorted(FEATURE_LIBRARY))


def random_spec(rng: random.Random, *, index: int = 0) -> StrategySpec:
    """One random spec from the grammar.

    Shallow on purpose: one or two comparisons per side. A searcher's early
    generations look like this, and depth adds evaluation cost without adding
    anything the gate treats differently.
    """
    # Through `parse` rather than the constructor, so a generated spec goes
    # through exactly the validation a searcher's or an LLM's output would.
    # Building the model directly would skip the discriminated-union coercion
    # and let this generator produce trees the real path could not.
    return StrategySpec.parse(
        {
            "name": f"null-{index:04d}",
            "entry": _predicate(rng),
            "exit": _predicate(rng),
            "expected_edge_bps": str(rng.choice(NULL_EDGES)),
            # Daily, since that is the only live resolution, and the
            # holding-period gate would otherwise refuse the whole population
            # for a reason that has nothing to do with whether its statistics
            # are noise.
            "min_holding_minutes": 1440,
            "notes": "generated by the null population for the false-promotion gate",
        }
    )


def _predicate(rng: random.Random) -> dict[str, object]:
    left = _term(rng)
    right = _term(rng)
    comparison: dict[str, object] = {
        "kind": "compare",
        "op": rng.choice(_COMPARISONS),
        "left": left,
        "right": right,
    }
    if rng.random() < 0.35:
        return {
            "kind": rng.choice(("all", "any")),
            "operands": [comparison, _simple_comparison(rng)],
        }
    return comparison


def _simple_comparison(rng: random.Random) -> dict[str, object]:
    return {
        "kind": "compare",
        "op": rng.choice(_COMPARISONS),
        "left": _feature(rng),
        "right": _term(rng),
    }


def _term(rng: random.Random) -> dict[str, object]:
    if rng.random() < 0.25:
        return {"kind": "const", "value": str(round(rng.uniform(-5, 120), 3))}
    return _feature(rng)


def _feature(rng: random.Random) -> dict[str, object]:
    lookback = rng.choice(NULL_LOOKBACKS)
    if not MIN_LOOKBACK <= lookback <= MAX_LOOKBACK:  # pragma: no cover - constants agree
        raise ValueError(f"lookback {lookback} is outside the grammar's bounds")
    return {"kind": "feature", "name": rng.choice(_FEATURES), "lookback": lookback}


def population(n: int, *, seed: int) -> list[StrategySpec]:
    """`n` distinct random specs, deterministic given the seed.

    Distinct by spec hash, because the registry deduplicates on it: a
    population containing the same tree twice would be one strategy and would
    make the denominator of the false-promotion rate a lie.
    """
    rng = random.Random(seed)  # noqa: S311 - a spec population, not a key
    seen: set[str] = set()
    out: list[StrategySpec] = []
    # Bounded so a degenerate grammar cannot spin forever. The space is far
    # larger than any n this is called with, so the bound is a safety net
    # rather than a working limit.
    attempts = 0
    while len(out) < n and attempts < n * 50:
        attempts += 1
        spec = random_spec(rng, index=len(out))
        # `name` carries the index, so two specs differing only in name would
        # both be kept; hash the tree without it.
        key = spec.spec_hash if spec.name == "" else _shape_hash(spec)
        if key in seen:
            continue
        seen.add(key)
        out.append(spec)
    if len(out) < n:  # pragma: no cover - the space is far larger than n
        raise ValueError(
            f"could only generate {len(out)} distinct specs out of {n} in {attempts} "
            "attempts; the grammar or the lookback set has been narrowed to the point "
            "where the population is not a sample of it"
        )
    return out


def _shape_hash(spec: StrategySpec) -> str:
    """The spec's hash ignoring its name.

    The name is an index the generator assigns, so two structurally identical
    specs would hash differently and both survive the deduplication — which
    would leave the population containing the same strategy twice while
    reporting a larger denominator.
    """
    from tb.core.canonical import hash_payload

    payload = spec.model_dump(mode="json")
    payload.pop("name", None)
    payload.pop("notes", None)
    return hash_payload(payload)


def random_walk_bars(
    *,
    instrument_uid: str,
    days: int,
    seed: int,
    start: datetime | None = None,
    volatility: float = 1.2,
) -> list[Bar]:
    """A price series with zero expected drift.

    No edge by construction. A strategy showing a positive Sharpe here found
    sampling noise, which is exactly what the false-promotion gate needs the
    population to be made of — measuring "no edge" on real prices would
    confound the gate's behaviour with whatever the decade did.
    """
    walk = random.Random(seed)  # noqa: S311 - a price fixture, not a key
    base = start or datetime(2020, 1, 2, tzinfo=UTC)
    price = Decimal("100.00")
    bars: list[Bar] = []
    for day in range(days):
        opened = base + timedelta(days=day)
        price = max(price + Decimal(str(round(walk.gauss(0, volatility), 4))), Decimal("1.00"))
        drift = Decimal(str(round(walk.gauss(0, volatility * 0.7), 4)))
        close = max(price + drift, Decimal("1.00"))
        bars.append(
            Bar(
                instrument_uid=instrument_uid,
                resolution=Resolution.DAILY,
                bar_open_utc=opened,
                available_at_utc=opened + timedelta(days=1),
                ingested_at_utc=opened + timedelta(days=1),
                provider="null_population",
                provenance=Provenance.BACKFILL,
                session=Session.REGULAR,
                open=price,
                high=max(price, close) + Decimal("0.50"),
                low=min(price, close) - Decimal("0.50"),
                close=close,
                volume=1_000_000,
                currency="USD",
            )
        )
    return bars


def decision_schedule(bars: Sequence[Bar], *, offset_hours: int = 1) -> list[datetime]:
    """One decision per bar, an hour after that bar became knowable.

    Derived from the bars rather than from a date range, so a schedule cannot
    drift out of step with the fixture it walks — a decision time with no
    knowable bar behind it produces an empty window, which reads as "the
    strategy declined" rather than "the schedule was wrong".
    """
    return [bar.available_at_utc + timedelta(hours=offset_hours) for bar in bars]
